# Generated by Django 4.2.7 on 2023-12-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iching_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(help_text='refresh')),
                ('access_token', models.CharField(help_text='access')),
                ('session_key', models.CharField(help_text='session_key')),
                ('session_secret', models.CharField(help_text='session_secret')),
                ('expires_in', models.IntegerField(default=0, help_text='expires')),
                ('scope_area', models.CharField(help_text='scope')),
            ],
            options={
                'db_table': 'token_record',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(default='用户1702352545', help_text='用户昵称', max_length=32),
        ),
    ]
