# Generated by Django 4.2.7 on 2023-12-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iching_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarecord',
            name='completion_tokens',
            field=models.IntegerField(default=0, help_text='完善token'),
        ),
        migrations.AddField(
            model_name='guarecord',
            name='prompt_tokens',
            field=models.IntegerField(default=0, help_text='参数token'),
        ),
        migrations.AddField(
            model_name='guarecord',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='token合计'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(default='用户1702962238', help_text='用户昵称', max_length=32),
        ),
    ]
