# Generated by Django 4.2.7 on 2024-01-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iching_main', '0002_guarecord_completion_tokens_guarecord_prompt_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwechat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='wechat_avatar/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(default='用户1704442716', help_text='用户昵称', max_length=32),
        ),
    ]
