# Generated by Django 4.2.7 on 2023-12-12 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iching_main', '0003_alter_userinfo_user_name_alter_tokenrecord_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenrecord',
            name='access_status',
            field=models.IntegerField(default=0, help_text='expires'),
        ),
        migrations.AddField(
            model_name='tokenrecord',
            name='update_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(default='用户1702357690', help_text='用户昵称', max_length=32),
        ),
    ]
